feat: add moments carousel
ariseasia/arise-asia-components pull request #9
Opened 2024-12-23 07:02 UTC by tamarayustian

2024-12-23 07:23 UTC, grenmester commented
the rounded borders on the image are cut off, can you fix it so it's applied properly

2024-12-23 07:24 UTC, grenmester commented
can the arrows used to page through the carousel be centered properly, on small viewports it gets shifted down, it should be centered on the image

2024-12-23 07:26 UTC, grenmester commented
non-blocking: if possible, can you make the height of the description box consistent, i.e. it doesn't change height between different slides. the different heights will lead to screen shift when users move through the carousel. ideally the height should be enough to cover the largest description

2024-12-23 07:26 UTC, grenmester commented on src/components/MomentsCarousel.jsx
> +  moments: PropTypes.arrayOf(
nit: `momentsData`

2024-12-23 07:28 UTC, grenmester requested changes
fix at least the two visual issues and if possible the other one too

2024-12-25 05:08 UTC, grenmester requested changes
looks good overall, last small comment, can we have the description be aligned to the bottom instead of the top so the gap that exists when a short description is in a large container is between the title and the description instead of the bottom of the container

2025-01-13 09:04 UTC, tamarayustian commented
> looks good overall, last small comment, can we have the description be aligned to the bottom instead of the top so the gap that exists when a short description is in a large container is between the title and the description instead of the bottom of the container

@grenmester I adjust the description to be centered and not totally at the end, because I think it looks better and neater. when I aligned it to the very bottom, the big gap looks awkward

2025-01-13 16:17 UTC, grenmester approved these changes

2025-01-13 16:18 UTC, merged